server:
  address: localhost
  port: 8888
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 2
        min-idle: 0
        max-wait: -1ms
    password:
    timeout: 300000ms
