---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35903.
--- DateTime: 2018/9/11 15:50
---
local key = "rate.limit:" .. KEYS[1];
local key2 = KEYS[2];
local limit = tonumber(key2);
local expire_time = ARGV[1];
local result = 0;

local is_exists = redis.call("EXISTS", key);
print("expire_time", expire_time, "is_exists ", is_exists, "key2", key2);
if is_exists == 1 then
    local incr_val = redis.call("INCR", key);
    print("incr_val ", incr_val, "limit", limit, "expire_time", expire_time);
    if incr_val < limit then
        redis.call("EXPIRE", key, expire_time);
        result = 1;
    end
else
    redis.call("SET", key, 1);
    redis.call("EXPIRE", key, expire_time);
    result = 1;
end
print("result ", result);
return result;